  Main.cpp
f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(20): warning C4244: 'inicializando': conversión de 'float' a 'int'; posible pérdida de datos
f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(230): warning C4244: '=': conversión de 'clock_t' a 'float'; posible pérdida de datos
f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(26): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(26): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(31): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(31): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(36): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(36): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(40): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(40): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(44): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(44): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(47): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(47): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(51): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(51): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(70): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(70): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(75): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(75): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(80): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(80): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(102): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(102): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(104): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(104): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(146): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(146): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(148): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(148): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(167): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(167): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(170): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(170): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
  AA2.vcxproj -> F:\2n Grado\Tecnologia_R\ActividadesTona\Actividades\\bin\Win32Debug\AA2.exe
  0 archivo(s) copiado(s)
